#!/usr/bin/env bash
# string 10 times using while loop

i=1

while [ "$i" -lt 11 ]; do
  echo "Best School"
  
  # if statement display Hi 
  if [ "$i" -eq 9 ]; then
    echo "Hi"
  fi

  ((i++))
done
